<a href="https://colab.research.google.com/github/pranitabhatkar35-creator/Data-Visualization/blob/main/NP_class_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,])
print("Array :\n",arr)
print("Shape :",arr.shape)
print("Dimensions :",arr.ndim)
print("Size :",arr.size)
print("Data type :",arr.dtype)

Array :
 [1 2 3 4 5 6]
Shape : (6,)
Dimensions : 1
Size : 6
Data type : int64


In [ ]:
arr1d=np.array([1,2,3,4,5])
print(arr1d[0])
print(arr1d[3])
print(arr1d[-4])

1
4
2


In [ ]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[0,2])

3


In [ ]:
arr1=np.array([1,2,3,4,5,])
print(arr1[1:4])
print(arr[:4])
print(arr[1:])

[2 3 4]
[1 2 3 4]
[2 3 4 5 6]


In [ ]:
arr1=np.array([10,20,30,40,50])
print(arr1[arr1>25])

[30 40 50]


In [ ]:
arr=np.array([1,2,3,4,5,6])
reshapeArr=arr.reshape(3,2)
print(reshapeArr)

[[1 2]
 [3 4]
 [5 6]]


In [2]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
flatten=arr.flatten()

[[1 2 3]
 [4 5 6]]
