<a href="https://colab.research.google.com/github/pranitabhatkar35-creator/Data-Visualization/blob/main/NP_Class_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Add two list**

In [ ]:
import numpy as np
a=[1,2,3,4]
b=[1,2,3,4]
print(a+b)

[1, 2, 3, 4, 1, 2, 3, 4]


**Add two array**

In [ ]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(a+b)

[2 4 6 8]


**Different operatons perform on array**

In [4]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(a-b)
print(a*b)
print(a//b)

[0 0 0 0]
[ 1  4  9 16]
[1 1 1 1]


**Broadcasting**

In [6]:
a=np.array([1,2,3,4])
print(a+5)
print(a-1)
print(a/2)

[6 7 8 9]
[0 1 2 3]
[0.5 1.  1.5 2. ]


**Operation Perform on 1D**

In [7]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[1,2,3]])
print(arr1+arr2)

[[2 4 6]
 [5 7 9]]


**Operation Perform on 2D**

In [8]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[1,2,3],[4,5,6]])
print(arr1+arr2)

[[ 2  4  6]
 [ 8 10 12]]


In [10]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[1,2,3],[4,5,6]])
print(arr1*2)

[[ 2  4  6]
 [ 8 10 12]]


In [11]:

arr1=np.array([[1,2,3],[4,5,6]])
print(arr1-1)

[[0 1 2]
 [3 4 5]]


In [12]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[1,2,3],[4,5,6]])
print(arr1-arr2)

[[0 0 0]
 [0 0 0]]
