<a href="https://colab.research.google.com/github/pranitabhatkar35-creator/Data-Visualization/blob/main/NP_Class_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[[1,0,2],[0,1,2]])

[4 2 9]


In [ ]:
arr=np.array([[3,1,2],[6,5,4],[8,9,7]])
print(np.argsort(arr))

[[1 2 0]
 [2 1 0]
 [2 0 1]]


In [ ]:
arr=np.array([[3,1,2],[6,5,4],[8,9,7]])
print(np.sort(arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.concatenate(arr))

[1 2 3 4 5 6 7 8 9]
