<a href="https://colab.research.google.com/github/pranitabhatkar35-creator/Data-Visualization/blob/main/NP_Class0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=[1,2,3,4,5]
print(a)
arr=np.array(a)
print("This is Array :",arr)

[1, 2, 3, 4, 5]
This is Array : [1 2 3 4 5]


In [ ]:
my_list=[[1,2,3],[4,5,6],[7,8,9]]
print(f"This is a list:{my_list}its type is {type(my_list)}")
my_arrMatrix=np.array(my_list)
print(f"This is matrix : \n{my_arrMatrix}\n its type is {my_arrMatrix.dtype}")


This is a list:[[1, 2, 3], [4, 5, 6], [7, 8, 9]]its type is <class 'list'>
This is matrix : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
 its type is int64


In [ ]:
vector=np.zeros(3)
print(f"This is a vector \n{vector}")
matrix=np.zeros((3,3))
print(f"This is a matrix \n{matrix}")

This is a vector 
[0. 0. 0.]
This is a matrix 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
vector=np.ones(3)
print(f"This is a vector \n{vector}")
matrix=np.ones((3,3))
print(f"This is a matrix \n{matrix}")


This is a vector 
[1. 1. 1.]
This is a matrix 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
vector=np.full(3,5)
print(f"This is a vector \n{vector}")
matrix=np.full((3,3),5)
print(f"This is a matrix \n{matrix}")

This is a vector 
[5 5 5]
This is a matrix 
[[5 5 5]
 [5 5 5]
 [5 5 5]]
