<a href="https://colab.research.google.com/github/pranitabhatkar35-creator/Data-Visualization/blob/main/NP_Class_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Create a list and perform a diiferent operation on it**


In [10]:
list=[1,2,3,4,5,6]
print(list)


list1=[1,"Pranita",2.8,True]
print(list1)

[1, 2, 3, 4, 5, 6]
[1, 'Pranita', 2.8, True]


**Operation perform on list**

In [23]:
a=[1,2,3]
b=[4,5,6]
print(a+b)
print(a*2)
print(a*3)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


**Create a array**

In [13]:
import numpy as np

arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


**Perform a different operation on array**

In [16]:
a=np.array([1,2,3,])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [17]:
print(a/b)
print(a//b)

[0.25 0.4  0.5 ]
[0 0 0]
