<a href="https://colab.research.google.com/github/pranitabhatkar35-creator/Data-Visualization/blob/main/NP_Class_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.arange(0,10,1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:

arr=np.linspace(0,10,5)
print(arr)


[ 0.   2.5  5.   7.5 10. ]


In [ ]:
arr=np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
