<a href="https://colab.research.google.com/github/pranitabhatkar35-creator/Data-Visualization/blob/main/NP_Class_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Aggregate Funcation**

Calculate the statistics arrays

In [2]:
import numpy as np
arr=np.array([4,1,3,15,18,10,22,35])
print("Sum",np.sum(arr))
print("Mean",np.mean(arr))
print("Min",np.min(arr))
print("Max",np.max(arr))
print("standard Devations",np.std(arr))
print("Variance",np.var(arr))



Sum 108
Mean 13.5
Min 1
Max 35
standard Devations 10.758717395675006
Variance 115.75


**Operation row-wise**

In [7]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("This is 2D array\n",arr2d)
print("Sum of all ele :",np.sum(arr2d))
print("Row wise sum of all ele:",np.sum (arr2d ,axis=1))

This is 2D array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of all ele : 45
Row wise sum of all ele: [12 15 18]


**Column wise**

In [9]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("This is 2D array\n",arr2d)
print("Sum of all ele :",np.sum(arr2d))
print("Col wise sum of all ele:",np.sum (arr2d ,axis=0))

This is 2D array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of all ele : 45
Col wise sum of all ele: [12 15 18]
