<a href="https://colab.research.google.com/github/pranitabhatkar35-creator/Data-Visualization/blob/main/NP_Class_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Fancy Indexing**

In [25]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr[0])
print(arr[[2,3]])
print(arr[[0,1]])

1
[3 4]
[1 2]


In [23]:
list=[1,2,3,4,5,6,7,8]
print(list)
print(list[0])
print(list[3])

[1, 2, 3, 4, 5, 6, 7, 8]
1
4


In [8]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print("Index accessing :")
print(arr[[1,2,0],[1,2,0]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Index accessing :
[5 9 1]


**Conditional selection**

In [10]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[arr>3])

[4 5 6 7 8]


In [15]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[arr%3==0])

[3 6 9]


In [19]:
arr=np.array([1,2,3,4,5,6,7,8])
arr[arr>4]=0
print(arr)

[1 2 3 4 0 0 0 0]
